"use strict";
const assert = require("node:assert/strict"), crypto = require("node:crypto"), http = require("node:http"), test = require("node:test");
const { Login, Registration } = require("@47ng/opaque-server");
const { createApp, alternateAddress } = require("../server");
const validHash = "A".repeat(43), b64 = (value) => Buffer.from(value).toString("base64url"), from = (value) => Buffer.from(value, "base64url");
async function withServer(options, run) { const service = createApp(options), server = http.createServer(service.app); await new Promise(resolve => server.listen(0, "127.0.0.1", resolve)); const origin = `http://127.0.0.1:${server.address().port}`; try { await run(origin, service); } finally { service.close(); await new Promise(resolve => server.close(resolve)); } }
async function post(origin, path, body) { return fetch(`${origin}${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); }
async function authenticate(origin, hash, pin) {
  const registration = new Registration(); const first = await post(origin, "/api/auth/register/start", { hash, request: b64(registration.start(pin)) }); assert.equal(first.status, 200); const begin = await first.json(); const record = registration.finish(pin, from(begin.response)); registration.free(); assert.equal((await post(origin, "/api/auth/register/finish", { nonce: begin.nonce, record: b64(record) })).status, 204);
  const login = new Login(); const loginStart = await post(origin, "/api/auth/login/start", { hash, request: b64(login.start(pin)) }); assert.equal(loginStart.status, 200); const challenge = await loginStart.json(); const finish = login.finish(pin, from(challenge.response)); const key = Buffer.from(login.getSessionKey()); login.free(); const session = await post(origin, "/api/auth/login/finish", { nonce: challenge.nonce, final: b64(finish) }); assert.equal(session.status, 200); return { ...(await session.json()), key };
}
async function loginAgain(origin, hash, pin) { const login = new Login(); const started = await post(origin, "/api/auth/login/start", { hash, request: b64(login.start(pin)) }); assert.equal(started.status, 200); const challenge = await started.json(); const final = login.finish(pin, from(challenge.response)); const key = Buffer.from(login.getSessionKey()); login.free(); const finished = await post(origin, "/api/auth/login/finish", { nonce: challenge.nonce, final: b64(final) }); assert.equal(finished.status, 200); return { ...(await finished.json()), key }; }
function proof(key, purpose, hash, messageHash = "", publicKey = "") { return crypto.createHmac("sha256", key).update(`${purpose}\n${hash}\n${messageHash}\n${publicKey}`).digest("base64url"); }

test("alternate address switches brands and keeps onion connections on onion", () => { assert.equal(alternateAddress("neutron.nxlabtw.com", "203.0.113.10"), "https://acmtn.nxlabtw.com/"); assert.match(alternateAddress("neutron.nxlabtw.com", "127.0.0.1"), /^http:\/\/acmtn\./); });
test("OPAQUE proves a PIN without POSTing it and grants a short RAM session", async () => withServer({}, async origin => { const session = await authenticate(origin, validHash, "correct horse battery staple"); assert.match(session.sessionId, /^[A-Za-z0-9_-]+$/); const prepared = await post(origin, "/api/message/prepare", { hash: validHash, sessionId: session.sessionId, proof: proof(session.key, "prepare", validHash) }); assert.equal(prepared.status, 200); const body = await prepared.json(); assert.match(body.messageHash, /^[A-Za-z0-9_-]{43}$/); assert.match(body.publicKey, /^[A-Za-z0-9_-]{43}$/); }));
test("an expired session can reauthenticate while the RAM-only OPAQUE record remains active", async () => withServer({ authTtlMs: 20, opaqueRecordTtlMs: 2000, cleanupIntervalMs: 5 }, async origin => { await authenticate(origin, validHash, "PIN"); await new Promise(resolve => setTimeout(resolve, 45)); const renewed = await loginAgain(origin, validHash, "PIN"); const prepared = await post(origin, "/api/message/prepare", { hash: validHash, sessionId: renewed.sessionId, proof: proof(renewed.key, "prepare", validHash) }); assert.equal(prepared.status, 200); }));
test("message descriptors never contain encrypted content and invalid writes are rejected", async () => withServer({}, async origin => { const session = await authenticate(origin, validHash, "PIN"); const rejected = await post(origin, "/api/message", { hash: validHash, sessionId: session.sessionId }); assert.equal(rejected.status, 401); const listed = await fetch(`${origin}/api/room?hash=${validHash}`); assert.deepEqual(await listed.json(), { v: 2, messages: [] }); }));
test("rejects malformed room hashes and protects headers", async () => withServer({}, async origin => { assert.equal((await fetch(`${origin}/api/room?hash=bad`)).status, 404); const response = await fetch(`${origin}/`); assert.match(response.headers.get("content-security-policy"), /default-src 'self'/); assert.match(response.headers.get("onion-location"), /neutron\./); }));
